### ISSUE TITLE
CLI interfaces needed!

### ISSUE THREAD

**Issue by KarelWintersky** [bminer/module-concat#1]
Subj!

**Comment by bminer** [comment]
@KarelWintersky - Any suggestions for node.js CLI libraries?  I've used [commander](https://github.com/tj/commander.js) in the past...

**Comment by KarelWintersky** [comment]
I mean command-line interface (tool)

**Comment by bminer** [comment]
Ya know what?  This tool already kinda works like a CLI... see https://github.com/bminer/node-module-concat/blob/master/index.js#L218

**Comment by bminer** [comment]
I'm going to close this issue for now, but if you have any questions or thoughts to improve the command-line interface, please let me know.  Thanks!
