### ISSUE TITLE
fileFooter cannot append correctly

### ISSUE THREAD

**Issue by cavoirom** [bminer/module-concat#2]
Hi bminer,
I would like to say thank for a simple and great tool. Today I found that in some case the fileFooter cannot append correctly, it cause this result:

``` java
exports.sample = sample;
//# sourceMappingURL=sample.js.mapreturn module.exports;
}
```

I try adding new line at the very first of fileFooter's content and can fix this issue.

**Comment by bminer** [comment]
Thanks for the bug report.  Sure, I can add a newline in the `fileFooter`.  Also thought about using curly braces, but I think the newline might be the easiest way.
