### ISSUE TITLE
The combined file has syntax errors

### ISSUE THREAD

**Issue by manve** [bminer/module-concat#5]
Hi guys,
I've used the code from your example and the combined file has been created successfully. 
```

C:\Work\DataFuel\Source>node src\build.js
8 were combined into ./concatenated.js
```

When I've tried to use this file the following error has been thrown.
```

C:\Work\DataFuel\Source>node concatenated.js
C:\Work\DataFuel\Source\concatenated.js:127
(function (exports, require, module, __getFilename("src\\server.js"), __getDirna
me("src\\server.js")) {
                                                  ^
SyntaxError: Unexpected token (
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

What is the reason of using the paths to the source files in the combined file?
What is happen after removing these paths? - the server has been started, but I do not sure that it is the right fix.

**Comment by bminer** [comment]
All instances of `__dirname` and `__filename` are replaced by node-module-concat.  It looks like you have those in a function header, which is technically not allowed.

I could provide an option to prevent this module from replacing those instances?

**Comment by manve** [comment]
I've rid of using the __dirname and __filename in header. Now it works.
that's amazing, thank you!

**Comment by bminer** [comment]
No problem!  :)
