### ISSUE TITLE
Failed to concat a few modules

### ISSUE THREAD

**Issue by RuiqiLi** [bminer/module-concat#6]
It seems like some modules failed to be concatenated when I used it on this repo: https://github.com/cheeriojs/cheerio

I found following require func calls in the output file:
``` javascript
return require("path").resolve(__dirname + "/" + path);
```
``` javascript
return require("path").resolve(__dirname + "/" + path + "/../");
```
``` javascript
__require(91,40)(Parser, require("events").EventEmitter);
```
``` javascript
var Parser = __require(40,46),
    WritableStream = require("stream").Writable || __require(98,46).Writable,
    StringDecoder = require("string_decoder").StringDecoder,
    Buffer = require("buffer").Buffer;
```

Have to say I am very appreciated for providing this helpful tool. I had been searching tools like this for hours and finally got this one. Thanks a lot.

**Comment by bminer** [comment]
No problem.  Can you post some more information here?  Do you get some sort of error message?  What exactly is the problem?  Can you tell me how to replicate?

**Comment by bminer** [comment]
I was able to concat the `cherrio` module with no issues.  Node's core modules (i.e. path, events, stream, string_decoder, buffer, etc.) are not replaced by module-concat.  Is that what you are talking about?

Closing this issue for now, but please feel free to post more information here.

**Comment by RuiqiLi** [comment]
Thanks for replying. Now I see what's my problem. I want to use the module in another runtime,  which doesn't have those build-in core modules.
Is there any way to concat them as well?

**Comment by bminer** [comment]
Interesting... what runtime?  Unfortunately, it seems like your problem is `cherrio`.  `cherrio` and many of its dependencies are designed only for the `node` engine.

Many of Node's core modules depend on native code in Node, so they cannot be concatenated for use outside of Node.

**Comment by RuiqiLi** [comment]
I'm not sure the runtime's name. An app named WeChat provides a runtime for js. You can use it to develop apps with native performance. It is like react-native. But it's not really an app installed in your phone. The app runs in WeChat.

Don't know if you ever heard about WeChat. It's popular in China. A very successful app in commercial.

I haven't try it yet. It's late night here and I will try it tomorrow. If it cannot work I have to find another module to parse html.

**Comment by bminer** [comment]
Interesting. Thanks for letting me know. You might be able to just use jQuery, but I don't know.

**Comment by RuiqiLi** [comment]
I've tried cheerio, and it worked in the simulater and Android device. Amazing. Haven't tried iOS yet. I'm afraid jQuery cannot help me, because it depends on window object and document object which are blocked by WeChat's runtime.

Thank you again for your help.
