### ISSUE TITLE
Trying to concat from another folder fails

### ISSUE THREAD

**Issue by tm1000** [bminer/module-concat#7]
Right now I'm having babel transpile my code into a separate build folder.

When I run module-concat against that build folder from the parent folder the resulting contact'ed file has 'build' in several places where __dirname are used. I've tried various combinations of the API to no success.

If I go into the build folder and execute module-concat from there it works. What I'm trying to do is it automate the process from a parent folder which doesnt work.

**Comment by bminer** [comment]
Are you passing the `outputPath` option to module-concat?  Can you post a little code here?

**Comment by tm1000** [comment]
Hi @bminer 
Initially I was running it this way which was failing (and I did try using ```outputPath``` without success...)
```
modConcat("build/index.js", "index.concat.js", {excludeNodeModules:true}, function(err, stats) {
						if(err) {
							console.error(err)
						}
					});
```
But now I am running it like so and it works!:
```
modConcat("build/index.js", "build/index.concat.js", {excludeNodeModules:true}, function(err, stats) {
						if(err) {
							console.error(err)
						}
						
					});
```

I am going to close this issue because the secondary path works fine.

Also I wanted to commend you on this project as it took me a few days to find something that concated nodejs modules correctly (grunt has a concat function but they don't treat the concated files like commonJS)

**Comment by bminer** [comment]
@tm1000 - Your issue makes more sense now. Your output file path affects how `__dirname` and `__filename` are resolved. I can't remember exactly how it works off of the top of my head, but... you can check out the code to learn more if you're ever interested. :)

Glad to hear that you like module-concat! I've been thinking about a gulp / grunt module with sourcemap support, but I haven't had the time to work on this yet.

**Comment by tm1000** [comment]
@bminer I started work on a grunt plugin for your module but it would strangely get stuck in the middle of the stream and just error out. Instead I'm running your module using grunt exec which allows me to run code within a grunt task.

**Comment by bminer** [comment]
@tm1000 - Cool. Yeah, I've never used grunt myself, so I can't really be of much help. I'm kind of waiting for Gulp v4 (sigh... years in the making) before investing time in building a Gulp plugin.
